default: &default
  adapter: postgresql
  encoding: unicode
  host: 172.17.0.2
  username: postgres
  password: 123456
  pool: 5

development:
  <<: *default
  database: c2s-scraping-service

test:
  <<: *default
  database: c2s-scraping-service-test